### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by steadygaze** [maxvanweenen/Nuxt-3-bootstrap-5-starter#2]
Hello, thanks for publishing this!

I noticed there is no license specified. By that, I mean there is neither a `LICENSE`/`LICENSE.md` file in the project root, nor a `license` property in the `package.json` (https://docs.npmjs.com/cli/v9/configuring-npm/package-json#license). Since this is a starter, I assume the intention is to publish this under a permissive license like MIT, ISC, etc. so others don't need to worry about the copyright status of the code when using it.

See also https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Also I guess just be careful that people don't accidentally license their project under the license that the starter is licensed as.

**Comment by maxvanweenen** [comment]
No problem, hopefully you get some use out of it!

And thanks for the heads-up, i'll get on that!

**Comment by maxvanweenen** [comment]
Added the license. Thanks again :)
